package estudos.maratonajava.javacore.Oexception.Runtime.test;

public class RuntimeException01 {
    public static void main(String[] args) {
        int[] nums = {1, 2};
        System.out.println(nums[2]);
    }
}
